[package]
name = "crypto_hash"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
digest = "0.10.2"
libc = "0.2"
md-5 = "0.10.2"
nserror = { path = "../../../../xpcom/rust/nserror" }
nsstring = { path = "../../../../xpcom/rust/nsstring" }
sha1 = "0.10.2"
sha2 = "0.10.2"
xpcom = { path = "../../../../xpcom/rust/xpcom" }
